#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  8 20:06:43 2020

@author: tulasiholdridge
"""
import numpy as np
from bs4 import BeautifulSoup
import requests


# create_lang_list : _ -> List
# creates an array of strings, where each string is a language
# under wikipedia's directory of Help:IPA pages
def create_lang_list():
    # use requests and beautiful soup to grab wiki page contents
    parent_url = 'https://en.wikipedia.org/wiki/Help:IPA'
    parent_page = requests.get(parent_url)
    directory_soup = BeautifulSoup(parent_page.content, 'html.parser')
    
    # narrow down content to the section we want
    table_container = directory_soup.find('div', attrs={'aria-labelledby' : 'International_Phonetic_Alphabet_keys'})
    table_section = table_container.find('td')
    table_links = table_section.find_all('a')
    
    # add urls to a list
    lang_dir_long = []
    for link in table_links:
        lang_dir_long.append(link.get('href')) # extract url from 'a' object
    
    # shorten to just language name as used in url
    lang_dir = []
    for link in lang_dir_long:
        lang_dir.append(link[15:])
        
    # return list of language names
    return lang_dir


# scrape_ipa_pages : List -> List
# navigates to the Help:IPA/[Language] page for every language in a list
# and puts its consonants in a new list of lists
def scrape_ipa_pages(lang_list):
    url_prefix = "https://en.wikipedia.org/wiki/Help:IPA/"
    # this won't be run often, so not worried about vectorization
    consonant_lists = [scrape_ipa(url_prefix + lang) for lang in lang_list]
    
    #return list of consonant lists
    return consonant_lists
    
# scrape_ipa : String -> List
# gets all IPA consonants from a url specified by the String, and returns
# them in list form
def scrape_ipa(lang):
    # use requests and beautiful soup to grab wiki page contents
    lang_page = requests.get(lang)
    soup = BeautifulSoup(lang_page.content, 'html.parser')
    
    # locate consonant table
    test_table_format = soup.find('a', attrs={'title' : 'Consonant'})
    
    # most pages are formatted a certain way, but some won't be
    if (test_table_format is None):
        # cheesing it for now
        return []
    
    # if it's the normal formatting, go through the procedure
    consonant_table_raw = test_table_format.parent.parent.parent
    consonant_table = consonant_table_raw.find_all('tr')[2:]
    consonant_links = [table_row.find('a') for table_row in consonant_table]
    
    #add consonants to a list
    consonants = []
    for link in consonant_links:
        consonants.append(link.contents)
    
    #return list of consonants
    return consonants
    

